environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

  matrix:
    - PYTHON: C:\Python27
      PYTHON_ARCH: '32'
      PYTHON_HOME: C:\python27
      PYTHON_VERSION: '2.7'
      TEST_LIBRARIES_ONLY: True
      TOXENV: 'py27'
      TOXPYTHON: C:\python27\python.exe
      WINDOWS_SDK_VERSION: v7.0

    - PYTHON: C:\Python27
      PYTHON_ARCH: '32'
      PYTHON_HOME: C:\python27
      PYTHON_VERSION: '2.7'
      TEST_LIBRARIES_ONLY: False
      TOXENV: 'py27'
      TOXPYTHON: C:\python27\python.exe
      WINDOWS_SDK_VERSION: v7.0

    - PYTHON: C:\Python34
      PYTHON_ARCH: '32'
      PYTHON_HOME: C:\python34
      PYTHON_VERSION: '3.4'
      TEST_LIBRARIES_ONLY: True
      TOXENV: 'py34'
      TOXPYTHON: C:\python34\python.exe
      WINDOWS_SDK_VERSION: v7.1

    - PYTHON: C:\Python34
      PYTHON_ARCH: '32'
      PYTHON_HOME: C:\python34
      PYTHON_VERSION: '3.4'
      TEST_LIBRARIES_ONLY: False
      TOXENV: 'py34'
      TOXPYTHON: C:\python34\python.exe
      WINDOWS_SDK_VERSION: v7.1

    - PYTHON: C:\Python35
      PYTHON_ARCH: '32'
      PYTHON_HOME: C:\python35
      PYTHON_VERSION: '3.5'
      TEST_LIBRARIES_ONLY: True
      TOXENV: 'py35'
      TOXPYTHON: C:\python35\python.exe
      WINDOWS_SDK_VERSION: v7.1

    - PYTHON: C:\Python35
      PYTHON_ARCH: '32'
      PYTHON_HOME: C:\python35
      PYTHON_VERSION: '3.5'
      TEST_LIBRARIES_ONLY: False
      TOXENV: 'py35'
      TOXPYTHON: C:\python35\python.exe
      WINDOWS_SDK_VERSION: v7.1

    - PYTHON: C:\Python36
      PYTHON_ARCH: '32'
      PYTHON_HOME: C:\python36
      PYTHON_VERSION: '3.6'
      TEST_LIBRARIES_ONLY: True
      TOXENV: 'py36'
      TOXPYTHON: C:\python36\python.exe
      WINDOWS_SDK_VERSION: v7.1

init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*

install:
  - python --version
  - pip install -r requirements.txt
  - pip install tox
  - pip install tox-travis
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version

build: none

test_script:
  - tox -v

after_test:
  - python setup.py bdist_wheel

artifacts:
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse

on_finish:
#  - ps: |
#      $wc = New-Object 'System.Net.WebClient'
#      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\nose2-junit.xml))

  - ps: >-
    If ($env:TOXENV -Match "py27") {
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\nosetests.xml))
    }
    
#    Else {
#      $wc = New-Object 'System.Net.WebClient'
#      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\nose2-junit.xml))
#    }
