environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

  matrix:
    - PYTHON: C:\Python27
      #PYTHON_VERSION: 2.7
      #PYTHON_ARCH: 32
      TOXENV: "py27"
      TEST_LIBRARIES_ONLY: True

    - PYTHON: C:\Python27
      #PYTHON_VERSION: 2.7
      #PYTHON_ARCH: 32
      TOXENV: "py27"
      TEST_LIBRARIES_ONLY: False

    - PYTHON: C:\Python34
      #PYTHON_VERSION: 3.4
      #PYTHON_ARCH: 32
      TOXENV: "py34"
      TEST_LIBRARIES_ONLY: True

    - PYTHON: C:\Python34
      #PYTHON_VERSION: 3.4
      #PYTHON_ARCH: 32
      TOXENV: "py34"
      TEST_LIBRARIES_ONLY: False

    - PYTHON: C:\Python35
      #PYTHON_VERSION: 3.5
      #PYTHON_ARCH: 32
      TOXENV: "py35"
      TEST_LIBRARIES_ONLY: True

    - PYTHON: C:\Python35
      #PYTHON_VERSION: 3.5
      #PYTHON_ARCH: 32
      TOXENV: "py35"
      TEST_LIBRARIES_ONLY: False

    - PYTHON: C:\Python36
      #PYTHON_VERSION: 3.6
      #PYTHON_ARCH: 32
      TOXENV: "py36"
      TEST_LIBRARIES_ONLY: True

    - PYTHON: C:\Python36
      #PYTHON_VERSION: 3.6
      #PYTHON_ARCH: 32
      TOXENV: "py36"
      TEST_LIBRARIES_ONLY: False

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - ECHO \"%APPVEYOR_SCHEDULED_BUILD%\"
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }

install:
  - python --version
  - pip install -r requirements.txt
  - pip install tox
  - pip install tox-travis
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version

build: none

test_script:
  - tox -v

after_test:
  - python setup.py bdist_wheel

artifacts:
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse

on_finish:
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\nose2-junit.xml))
